### ISSUE TITLE
Error trying to connect using CE

### ISSUE THREAD

**Issue by LukaTheHero** [isabellaflores/ceserver-pcileech#2]
Cheat Engine gives me the following error:
I can't get the process list. You are probably using windows NT. Use the window list instead! 

Here's the log from ceserver as well.

[2022-08-16 00:06:13.694 Client-00002] Connection from 127.0.0.1
[2022-08-16 00:06:13.699 Client-00002] Connection closed.
Exception in thread "Client-00002 [127.0.0.1]" iflores.ceserver.pcileech.PciLeechException
	at iflores.ceserver.pcileech.PciLeech.getPids(PciLeech.java:41)
	at iflores.ceserver.pcileech.ToolHelp32Snapshot_Processes.<init>(ToolHelp32Snapshot_Processes.java:23)
	at iflores.ceserver.pcileech.ClientHandler.handleCommand(ClientHandler.java:129)
	at iflores.ceserver.pcileech.ClientHandler.run(ClientHandler.java:86)

Is the project outdated or am I doing something wrong?

**Comment by LukaTheHero** [comment]
I have solved the issue. I was using [MemProcFS_files_and_binaries_v5.0.3-win_x64-20220818]
I switched to [MemProcFS_files_and_binaries_v4.8.4-win_x64-20220604]

Now it works. If anyone else is having the same issue this fixes it.
